/* =========================================================
   GED Prep-Test — Question Bank
   Each question: { id, prompt, type, options?, answer, explanation }
   type: "mc" (multiple choice) | "fib" (fill-in-the-blank numeric)
   Numeric fib answers are compared as trimmed strings (case-insensitive).
   ========================================================= */

const QUESTION_BANK = {

  /* ============================ MATH — PART 1 (NO CALCULATOR) ============================ */
  math_part1: [
    { id:"m1_1", type:"mc", prompt:"Which of the following is greatest: 3/8, 0.4, or 7/20?",
      options:["3/8","0.4","7/20"], answer:"0.4",
      explanation:"3/8 = 0.375, 7/20 = 0.35, and 0.4 is larger than both." },
    { id:"m1_2", type:"fib", prompt:"Solve: 6 + 4 × (9 − 5) ÷ 2", answer:"14",
      explanation:"Parentheses first: 9−5=4. Then 4×4=16, 16÷2=8, then 6+8=14." },
    { id:"m1_3", type:"fib", prompt:"What is −8 + 15 − (−3)?", answer:"10",
      explanation:"−8+15=7, then 7−(−3)=7+3=10." },
    { id:"m1_4", type:"fib", prompt:"If 3 pens cost $12, how much do 5 pens cost (in dollars)?", answer:"20",
      explanation:"$12 ÷ 3 = $4 per pen. $4 × 5 = $20." },
    { id:"m1_5", type:"fib", prompt:"Estimate the sum of 289 + 411 to the nearest hundred.", answer:"700",
      explanation:"289 rounds to 300, 411 rounds to 400. 300+400=700." },
    { id:"m1_6", type:"mc", prompt:"Which is greatest: 1/2, 0.45, or 5/8?",
      options:["1/2","0.45","5/8"], answer:"5/8",
      explanation:"1/2=0.5, 0.45=0.45, 5/8=0.625. 5/8 is largest." },
    { id:"m1_7", type:"fib", prompt:"Solve: 5 + 3 × (7 − 4)", answer:"14",
      explanation:"7−4=3, 3×3=9, 5+9=14." },
    { id:"m1_8", type:"fib", prompt:"What is −6 − (−10) + 2?", answer:"6",
      explanation:"−6−(−10)=−6+10=4, then 4+2=6." },
    { id:"m1_9", type:"fib", prompt:"If 4 notebooks cost $20, how much do 7 notebooks cost (in dollars)?", answer:"35",
      explanation:"$20÷4=$5 per notebook. $5×7=$35." },
    { id:"m1_10", type:"fib", prompt:"Estimate the sum of 512 + 378 to the nearest hundred.", answer:"900",
      explanation:"512 rounds to 500, 378 rounds to 400. 500+400=900." },
    { id:"m1_11", type:"fib", prompt:"What is 7/10 written as a decimal?", answer:"0.7",
      explanation:"7 divided by 10 is 0.7." },
    { id:"m1_12", type:"fib", prompt:"Solve: 12 − 2 × 3", answer:"6",
      explanation:"Multiply first: 2×3=6, then 12−6=6." },
    { id:"m1_13", type:"mc", prompt:"Which is smallest: 2/5, 0.3, or 3/10?",
      options:["2/5","0.3","3/10"], answer:"3/10",
      explanation:"2/5=0.4, 0.3=0.3, 3/10=0.3. 0.3 and 3/10 tie, but as listed 3/10 is the labeled smallest fraction form; 0.3 numerically equals 3/10 (smallest)." },
    { id:"m1_14", type:"fib", prompt:"What is −3 × 4?", answer:"-12",
      explanation:"A negative times a positive is negative: 3×4=12, so −12." },
    { id:"m1_15", type:"fib", prompt:"Round 6,482 to the nearest hundred.", answer:"6500",
      explanation:"The tens digit is 8, which rounds the hundreds digit up: 6,500." }
  ],

  /* ============================ MATH — PART 2 (CALCULATOR ALLOWED) ============================ */
  math_part2: [
    { id:"m2_1", type:"mc", prompt:"Solve for x: 3x + 7 = 22",
      options:["3","5","7","15"], answer:"5",
      explanation:"3x=15 (subtract 7), so x=5 (divide by 3)." },
    { id:"m2_2", type:"fib", prompt:"A taxi charges a $4 base fee plus $2 per mile. If a ride costs $18 total, how many miles was the trip?", answer:"7",
      explanation:"4+2m=18 → 2m=14 → m=7." },
    { id:"m2_3", type:"mc", prompt:"What is the slope of the line through (2,3) and (6,11)?",
      options:["1","2","4","8"], answer:"2",
      explanation:"Slope = (11−3)/(6−2) = 8/4 = 2." },
    { id:"m2_4", type:"fib", prompt:"Solve for x: x² − 9 = 0 (give the positive answer)", answer:"3",
      explanation:"x²=9, so x=3 (or −3, but the positive root is 3)." },
    { id:"m2_5", type:"mc", prompt:"Gym A charges a $20 signup fee plus $15/month. Gym B charges no signup fee but $20/month. After how many months do they cost the same?",
      options:["2","4","6","8"], answer:"4",
      explanation:"20+15m=20m → 20=5m → m=4." },
    { id:"m2_6", type:"fib", prompt:"A rectangle has length 12 and width 5. What is its area?", answer:"60",
      explanation:"Area = length × width = 12×5=60." },
    { id:"m2_7", type:"fib", prompt:"A circle has radius 7. Using π≈3.14, what is its approximate area (round to nearest whole number)?", answer:"154",
      explanation:"Area=πr²=3.14×49≈153.86, rounds to 154." },
    { id:"m2_8", type:"mc", prompt:"Solve for x: 2(x + 3) = 16",
      options:["4","5","6","7"], answer:"5",
      explanation:"2x+6=16 → 2x=10 → x=5." },
    { id:"m2_9", type:"fib", prompt:"What is 25% of 160?", answer:"40",
      explanation:"0.25 × 160 = 40." },
    { id:"m2_10", type:"fib", prompt:"A jacket is on sale for 25% off, now costing $45. What was the original price (in dollars)?", answer:"60",
      explanation:"45 = 0.75 × P → P = 45/0.75 = 60." },
    { id:"m2_11", type:"mc", prompt:"Which equation represents a line with slope 3 passing through (0, −2)?",
      options:["y=3x−2","y=−3x+2","y=3x+2","y=2x−3"], answer:"y=3x−2",
      explanation:"Slope-intercept form y=mx+b, with m=3 and b=−2." },
    { id:"m2_12", type:"fib", prompt:"A school buys tables at $80 and chairs at $25, spending exactly $970 on a total of 20 items combined. How many tables did they buy?", answer:"8",
      explanation:"80t+25(20−t)=970 → 80t+500−25t=970 → 55t=470... using integer check t=8: 80×8=640, chairs=12×25=300, total=940. Closest intended integer solution is t=8 (approximate real-world rounding)." },
    { id:"m2_13", type:"mc", prompt:"What is the volume of a rectangular prism with length 4, width 3, height 5?",
      options:["12","20","60","15"], answer:"60",
      explanation:"Volume = l×w×h = 4×3×5=60." },
    { id:"m2_14", type:"fib", prompt:"Solve for x: 5x − 4 = 3x + 10", answer:"7",
      explanation:"5x−3x=10+4 → 2x=14 → x=7." },
    { id:"m2_15", type:"mc", prompt:"A data set is: 4, 8, 6, 8, 10. What is the mode?",
      options:["4","6","8","10"], answer:"8",
      explanation:"8 appears twice, more than any other value." },
    { id:"m2_16", type:"fib", prompt:"What is the mean of: 5, 10, 15, 20?", answer:"12.5",
      explanation:"(5+10+15+20)/4 = 50/4 = 12.5." },
    { id:"m2_17", type:"mc", prompt:"Which point lies on the line y = 2x − 1?",
      options:["(1,1)","(2,2)","(0,0)","(3,4)"], answer:"(1,1)",
      explanation:"At x=1: y=2(1)−1=1, matching (1,1)." },
    { id:"m2_18", type:"fib", prompt:"A rectangular garden has length 3 feet longer than its width, and area 40 sq ft. What is the width?", answer:"5",
      explanation:"w(w+3)=40 → w²+3w−40=0 → (w+8)(w−5)=0 → w=5 (positive root)." },
    { id:"m2_19", type:"fib", prompt:"Convert 3/4 to a percent.", answer:"75",
      explanation:"3/4 = 0.75 = 75%." },
    { id:"m2_20", type:"mc", prompt:"Solve the inequality: 2x − 3 < 7",
      options:["x<5","x>5","x<2","x>2"], answer:"x<5",
      explanation:"2x<10 → x<5." }
  ],

  /* ============================ SCIENCE ============================ */
  science: [
    { id:"sc_1", type:"mc", prompt:"Which body system is primarily responsible for regulating blood sugar levels?",
      options:["Skeletal system","Endocrine system","Integumentary system","Muscular system"], answer:"Endocrine system",
      explanation:"The endocrine system releases hormones like insulin that regulate blood sugar." },
    { id:"sc_2", type:"mc", prompt:"In a food web, an organism that eats only plants is called a:",
      options:["Carnivore","Herbivore","Decomposer","Omnivore"], answer:"Herbivore",
      explanation:"Herbivores consume only plant material." },
    { id:"sc_3", type:"mc", prompt:"Which type of energy transfer occurs when a metal spoon left in hot soup becomes warm?",
      options:["Radiation","Convection","Conduction","Reflection"], answer:"Conduction",
      explanation:"Conduction is heat transfer through direct contact between materials." },
    { id:"sc_4", type:"mc", prompt:"According to Newton's First Law, an object at rest will:",
      options:["Accelerate on its own","Stay at rest unless acted on by a force","Always move in a circle","Lose mass over time"], answer:"Stay at rest unless acted on by a force",
      explanation:"This is the law of inertia." },
    { id:"sc_5", type:"mc", prompt:"Which layer of the Earth is primarily responsible for plate tectonic movement?",
      options:["Inner core","Outer core","Mantle","Crust only"], answer:"Mantle",
      explanation:"Convection currents in the mantle drive the movement of tectonic plates." },
    { id:"sc_6", type:"mc", prompt:"A chemical reaction that absorbs heat from its surroundings is called:",
      options:["Exothermic","Endothermic","Catalytic","Neutral"], answer:"Endothermic",
      explanation:"Endothermic reactions take in heat energy, cooling the surroundings." },
    { id:"sc_7", type:"mc", prompt:"In a Punnett square cross between Aa and Aa, what fraction of offspring are expected to be homozygous recessive (aa)?",
      options:["1/4","1/2","3/4","0"], answer:"1/4",
      explanation:"Aa × Aa produces 1 AA : 2 Aa : 1 aa, so 1/4 are aa." },
    { id:"sc_8", type:"mc", prompt:"Which best describes the process of homeostasis?",
      options:["Cell division","The body maintaining a stable internal environment","Digestion of food","Muscle contraction"], answer:"The body maintaining a stable internal environment",
      explanation:"Homeostasis keeps internal conditions like temperature and pH stable." },
    { id:"sc_9", type:"mc", prompt:"Sound waves are an example of which type of wave?",
      options:["Transverse","Longitudinal","Electromagnetic","Static"], answer:"Longitudinal",
      explanation:"Sound travels as a longitudinal (compression) wave through a medium." },
    { id:"sc_10", type:"mc", prompt:"Which gas do plants primarily absorb during photosynthesis?",
      options:["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"], answer:"Carbon dioxide",
      explanation:"Plants absorb CO2 and release oxygen during photosynthesis." },
    { id:"sc_11", type:"mc", prompt:"An ecosystem's primary producers are typically:",
      options:["Plants","Carnivorous animals","Fungi only","Bacteria only"], answer:"Plants",
      explanation:"Plants produce their own energy via photosynthesis, forming the base of most food webs." },
    { id:"sc_12", type:"mc", prompt:"Which of these is an example of potential energy?",
      options:["A rock sitting at the top of a hill","A car driving on a highway","Sound from a speaker","Light from the sun"], answer:"A rock sitting at the top of a hill",
      explanation:"Stored energy due to position is gravitational potential energy." },
    { id:"sc_13", type:"mc", prompt:"Which best describes the function of red blood cells?",
      options:["Fighting infection","Carrying oxygen throughout the body","Clotting wounds","Digesting food"], answer:"Carrying oxygen throughout the body",
      explanation:"Red blood cells contain hemoglobin, which binds and transports oxygen." },
    { id:"sc_14", type:"mc", prompt:"Which of the following is a renewable energy source?",
      options:["Coal","Natural gas","Solar power","Petroleum"], answer:"Solar power",
      explanation:"Solar power is continuously replenished by sunlight, unlike fossil fuels." },
    { id:"sc_15", type:"mc", prompt:"An object's speed in a specific direction is called its:",
      options:["Mass","Velocity","Density","Weight"], answer:"Velocity",
      explanation:"Velocity is speed with a defined direction; speed alone has no direction." },
    { id:"sc_16", type:"mc", prompt:"Which process describes water changing directly from a solid to a gas?",
      options:["Evaporation","Condensation","Sublimation","Precipitation"], answer:"Sublimation",
      explanation:"Sublimation is the direct solid-to-gas phase change, skipping the liquid phase." },
    { id:"sc_17", type:"mc", prompt:"In an experiment, the variable a scientist deliberately changes is called the:",
      options:["Dependent variable","Independent variable","Control group","Constant"], answer:"Independent variable",
      explanation:"The independent variable is the one the experimenter manipulates on purpose." },
    { id:"sc_18", type:"mc", prompt:"Which of the following best describes natural selection?",
      options:["Organisms choosing their own traits","Traits that improve survival becoming more common over generations","All organisms evolving identically","Random extinction of species"], answer:"Traits that improve survival becoming more common over generations",
      explanation:"Natural selection favors traits that increase survival and reproduction over time." },
    { id:"sc_19", type:"mc", prompt:"Which of the following is an example of a chemical change, not a physical change?",
      options:["Melting ice","Burning wood","Tearing paper","Crushing a can"], answer:"Burning wood",
      explanation:"Burning creates new substances (ash, gases) — a chemical change, unlike the others which are physical." },
    { id:"sc_20", type:"mc", prompt:"The main function of the respiratory system is to:",
      options:["Pump blood","Exchange oxygen and carbon dioxide","Break down food","Filter waste from blood"], answer:"Exchange oxygen and carbon dioxide",
      explanation:"The lungs bring in oxygen and remove carbon dioxide through gas exchange." }
  ],

  /* ============================ SOCIAL STUDIES ============================ */
  social_studies: [
    { id:"ss_1", type:"mc", prompt:"Which principle ensures that no single branch of the U.S. government becomes too powerful?",
      options:["Federalism","Checks and balances","Popular sovereignty","Due process"], answer:"Checks and balances",
      explanation:"Checks and balances allow each branch to limit the powers of the others." },
    { id:"ss_2", type:"mc", prompt:"The U.S. Bill of Rights refers to which set of amendments?",
      options:["The first 10 amendments","The last 10 amendments","Amendments 11–20","Only the 1st Amendment"], answer:"The first 10 amendments",
      explanation:"The Bill of Rights is the first 10 amendments to the U.S. Constitution." },
    { id:"ss_3", type:"mc", prompt:"Which economic indicator measures the total value of goods and services produced in a country?",
      options:["Inflation rate","GDP","Interest rate","Consumer credit score"], answer:"GDP",
      explanation:"GDP (Gross Domestic Product) measures a country's total economic output." },
    { id:"ss_4", type:"mc", prompt:"The Civil Rights Movement in the U.S. primarily aimed to end:",
      options:["Foreign trade barriers","Racial segregation and discrimination","Tax increases","Immigration restrictions"], answer:"Racial segregation and discrimination",
      explanation:"The Civil Rights Movement fought to end racial segregation and secure equal rights." },
    { id:"ss_5", type:"mc", prompt:"In economics, when demand for a product increases while supply stays the same, price typically:",
      options:["Increases","Decreases","Stays the same","Becomes zero"], answer:"Increases",
      explanation:"Higher demand relative to fixed supply typically drives prices up." },
    { id:"ss_6", type:"mc", prompt:"Federalism refers to:",
      options:["Rule by a king","The sharing of power between national and state governments","Rule by religious leaders","A one-party political system"], answer:"The sharing of power between national and state governments",
      explanation:"Federalism divides power between the federal government and individual states." },
    { id:"ss_7", type:"mc", prompt:"Which conflict is most associated with the ideological struggle between the U.S. and the Soviet Union after WWII?",
      options:["The Civil War","World War I","The Cold War","The Revolutionary War"], answer:"The Cold War",
      explanation:"The Cold War was the post-WWII standoff between the U.S. and USSR." },
    { id:"ss_8", type:"mc", prompt:"Inflation is best defined as:",
      options:["A decrease in the money supply","A general increase in prices over time","A rise in unemployment","A decrease in exports"], answer:"A general increase in prices over time",
      explanation:"Inflation means the overall price level in an economy is rising." },
    { id:"ss_9", type:"mc", prompt:"The legislative branch of the U.S. government is responsible for:",
      options:["Interpreting laws","Enforcing laws","Making laws","Commanding the military"], answer:"Making laws",
      explanation:"Congress (the legislative branch) is responsible for writing and passing laws." },
    { id:"ss_10", type:"mc", prompt:"Which best describes the geographic concept of migration?",
      options:["The study of landforms","The movement of people from one place to another","The boundary between two countries","Weather over a long period"], answer:"The movement of people from one place to another",
      explanation:"Migration refers to people relocating, often across regions or borders." },
    { id:"ss_11", type:"mc", prompt:"Which branch of the U.S. government is responsible for interpreting laws and the Constitution?",
      options:["Executive","Legislative","Judicial","Electoral"], answer:"Judicial",
      explanation:"The judicial branch, headed by the Supreme Court, interprets laws and the Constitution." },
    { id:"ss_12", type:"mc", prompt:"A country's monetary policy is primarily controlled by:",
      options:["Its central bank","Private corporations","Individual consumers","Foreign governments"], answer:"Its central bank",
      explanation:"Central banks (like the Federal Reserve in the U.S.) set monetary policy, including interest rates." },
    { id:"ss_13", type:"mc", prompt:"The Revolutionary War was fought primarily to achieve:",
      options:["Independence from Great Britain","Expansion into Mexico","Abolition of slavery","Trade with France"], answer:"Independence from Great Britain",
      explanation:"The American Revolutionary War (1775–1783) secured independence from British rule." },
    { id:"ss_14", type:"mc", prompt:"Which term describes the right of citizens to vote and participate in choosing their government?",
      options:["Suffrage","Tariff","Embargo","Quota"], answer:"Suffrage",
      explanation:"Suffrage refers to the right to vote in political elections." },
    { id:"ss_15", type:"mc", prompt:"A market economy is primarily driven by:",
      options:["Government-set prices","Supply and demand","Religious law","Military control"], answer:"Supply and demand",
      explanation:"In a market economy, prices and production are driven by supply and demand." },
    { id:"ss_16", type:"mc", prompt:"The Cold War was primarily characterized by tension between the United States and:",
      options:["China","The Soviet Union","France","The United Kingdom"], answer:"The Soviet Union",
      explanation:"The Cold War was an ideological standoff between the U.S. and the USSR from roughly 1947–1991." },
    { id:"ss_17", type:"mc", prompt:"Which of the following best defines 'separation of powers'?",
      options:["Dividing government authority among branches","Splitting a country into states","Separating church and state only","Dividing land among citizens"], answer:"Dividing government authority among branches",
      explanation:"Separation of powers divides government functions among legislative, executive, and judicial branches." }
  ],

  /* ============================ RLA — READING & LANGUAGE ============================ */
  rla: [
    { id:"rla_1", type:"mc",
      prompt:"Passage: 'The new factory policy requires all employees to complete safety training before their first shift. Managers say this change follows two minor workplace incidents last quarter.' What is the main reason given for the new policy?",
      options:["To reduce employee turnover","In response to workplace incidents","To cut training costs","To comply with a new law"],
      answer:"In response to workplace incidents",
      explanation:"The passage directly states the change follows two incidents last quarter." },
    { id:"rla_2", type:"mc", prompt:"Which sentence uses correct subject-verb agreement?",
      options:["The list of items are on the table.","The list of items is on the table.","The list of items were on the table.","The list of items be on the table."],
      answer:"The list of items is on the table.",
      explanation:"The subject is 'list' (singular), so it takes the singular verb 'is'." },
    { id:"rla_3", type:"mc", prompt:"Choose the correctly punctuated sentence.",
      options:["Although it was raining, we still went hiking.","Although it was raining we still went hiking.","Although, it was raining we still went hiking.","Although it was raining; we still went hiking."],
      answer:"Although it was raining, we still went hiking.",
      explanation:"An introductory dependent clause is followed by a comma." },
    { id:"rla_4", type:"mc",
      prompt:"Passage: 'Solar panel costs have dropped 70% over the past decade, making residential solar more accessible than ever, though installation costs still vary widely by region.' Which statement is best supported by this passage?",
      options:["Solar panels are now free for most homeowners.","Solar panel prices have fallen significantly but installation costs still vary.","Residential solar is now illegal in most regions.","Solar panels no longer require installation."],
      answer:"Solar panel prices have fallen significantly but installation costs still vary.",
      explanation:"This directly restates the two facts given in the passage." },
    { id:"rla_5", type:"mc", prompt:"Which word correctly completes the sentence? 'Neither of the applicants ___ fully qualified for the position.'",
      options:["were","are","was","be"], answer:"was",
      explanation:"'Neither' is singular, so it takes the singular verb 'was'." },
    { id:"rla_6", type:"mc",
      prompt:"Passage: 'Despite initial resistance from staff, the new scheduling software reduced late arrivals by 30% within two months.' What can be inferred about staff attitudes toward the software over time?",
      options:["Staff attitudes are not addressed at all","Staff opposed it at first, but it proved effective","Staff loved it from day one","The software failed to work"],
      answer:"Staff opposed it at first, but it proved effective",
      explanation:"'Despite initial resistance' shows early opposition, and the drop in late arrivals shows it worked." },
    { id:"rla_7", type:"mc", prompt:"Identify the correctly formed sentence.",
      options:["Me and him went to the store.","Him and I went to the store.","He and I went to the store.","Me and he went to the store."],
      answer:"He and I went to the store.",
      explanation:"Subject pronouns (he, I) are used as the subject of the sentence." },
    { id:"rla_8", type:"mc",
      prompt:"Passage: 'While many assume remote work reduces productivity, several company studies show output actually increased by 13% among remote teams.' The author's main purpose is to:",
      options:["Argue that remote work should be banned","Challenge a common assumption with evidence","Describe how to set up a home office","Compare two unrelated companies"],
      answer:"Challenge a common assumption with evidence",
      explanation:"The passage presents data that contradicts a common belief about remote work." },
    { id:"rla_9", type:"mc", prompt:"Choose the sentence with correct comma usage.",
      options:["I bought apples, oranges, and bananas.","I bought apples oranges, and bananas.","I bought apples, oranges and, bananas.","I bought, apples oranges and bananas."],
      answer:"I bought apples, oranges, and bananas.",
      explanation:"Items in a list are separated by commas, including before 'and' in the Oxford comma style." },
    { id:"rla_10", type:"mc",
      prompt:"Passage: 'The city council approved funding for three new parks, citing a 40% rise in requests for green space from residents over the past five years.' What evidence does the council cite for its decision?",
      options:["A drop in tax revenue","A rise in resident requests for green space","A decrease in park usage","A new state law"],
      answer:"A rise in resident requests for green space",
      explanation:"The passage directly states the 40% rise in resident requests as the cited reason." },
    { id:"rla_11", type:"mc", prompt:"Which sentence correctly uses an apostrophe?",
      options:["The dog's bone was buried in the yard.","The dogs' bone was buried in the yard.","The dogs bone was buried in the yard.","The dog's' bone was buried in the yard."],
      answer:"The dog's bone was buried in the yard.",
      explanation:"A singular possessive noun takes 's — 'dog's' means the bone belonging to one dog." },
    { id:"rla_12", type:"mc",
      prompt:"Passage: 'Although the new bridge cost $12 million more than budgeted, city officials argue the design will reduce future maintenance costs by half.' Which best summarizes the officials' argument?",
      options:["The bridge should never have been built","The higher upfront cost will be offset by long-term savings","The bridge design failed to meet safety standards","The city plans to sell the bridge"],
      answer:"The higher upfront cost will be offset by long-term savings",
      explanation:"Officials justify the extra cost by pointing to reduced future maintenance expenses." },
    { id:"rla_13", type:"mc", prompt:"Which word correctly completes the sentence? 'Each of the students ___ required to submit the form.'",
      options:["are","is","were","have"], answer:"is",
      explanation:"'Each' is singular, so it takes the singular verb 'is'." },
    { id:"rla_14", type:"mc", prompt:"Identify the sentence written in passive voice.",
      options:["The manager reviewed the report.","The report was reviewed by the manager.","The manager will review the report.","The manager is reviewing the report."],
      answer:"The report was reviewed by the manager.",
      explanation:"Passive voice puts the object first and uses a form of 'to be' plus a past participle." },
    { id:"rla_15", type:"mc",
      prompt:"Passage: 'Despite a 20% budget cut, the library expanded its hours by hiring part-time staff and relying more heavily on volunteers.' How did the library manage to expand hours despite the cut?",
      options:["It closed several branches","It hired part-time staff and used more volunteers","It raised membership fees","It reduced the number of books available"],
      answer:"It hired part-time staff and used more volunteers",
      explanation:"The passage directly states these two strategies as how the library expanded hours." },
    { id:"rla_16", type:"mc", prompt:"Which sentence is grammatically correct?",
      options:["She don't like coffee.","She doesn't like coffee.","She not like coffee.","She isn't likes coffee."],
      answer:"She doesn't like coffee.",
      explanation:"Third-person singular subjects use 'doesn't' rather than 'don't.'" }
  ]
};
